language: go
sudo: false
go_import_path: github.com/daripadabengong/oauth2/v4
go:
  - 1.13
before_install:
  - go get -t -v ./...

script:
  - chmod +x ./go.test.sh && ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
